server:
  port: 8761
spring:
  application:
    name: naming-server
eureka:
  client:
    register-with-eureka: false   #Nâo pode se auto registrar através das vairas instancias
    fetch-registry: false
